default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reading_asset_development
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>

test:
  <<: *default
  database: reading_asset_test
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>

staging:
  <<: *default
  database: reading_asset_staging
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>

production:
  <<: *default
  database: reading_asset
  username: <%= ENV['MYSQL_ROOT_USER'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"
